version: '3'

services:
  redis:
    image: redis:latest
    ports:
      - "6380:6379"
    volumes:
      - ./data/redis:/data

  motus1:
    build: .
    ports:
      - "3001:3000"
    environment:
      - API_PATH=./data/liste_francais_utf8.txt
      - SCORE_URI=http://score:4000
      - OAUTH_URI=http://localhost:7001
      - REDIRECT_URI=http://localhost:3001/callback
      - SECRET=BXFykXgWZUsK_voVdppdhLHET7VbpAIymruA___6QL08IqoiWHv5vzifJ5guZf
      - CLIENTID=rwhxUXp6RD7h3kmFnFG54H8gd1cV2SYJ

  score:
    build: ./../score
    ports:
      - "4001:4000"
    environment:
      - REDIS=redis://redis:6379

  oauth:
    build: ./../oauth
    ports:
      - "7001:7000"
    environment:
      - REDIS=redis://redis:6379
      - SECRET=BXFykXgWZUsK_voVdppdhLHET7VbpAIymruA___6QL08IqoiWHv5vzifJ5guZf
      - CLIENTID=rwhxUXp6RD7h3kmFnFG54H8gd1cV2SYJ
      - REDIRECT_URI=http://localhost:3001/callback
    

  haproxy:
    build: 
      context: .
      dockerfile: Dockerfile-haproxy
    ports:
      - "8083:83"
      - "8404:8404"
    depends_on:
      - motus1
      - score
      - oauth
    restart: always

networks:
  monitor-net:
